//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnalyzerTemplate {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AnalyzerTemplate.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method must returns a collection.
        /// </summary>
        internal static string AnalyzerI7Description {
            get {
                return ResourceManager.GetString("AnalyzerI7Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method must returns a collection .
        /// </summary>
        internal static string AnalyzerI7MessageFormat {
            get {
                return ResourceManager.GetString("AnalyzerI7MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method must returns a collection.
        /// </summary>
        internal static string AnalyzerI7Title {
            get {
                return ResourceManager.GetString("AnalyzerI7Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method must returns a collection.
        /// </summary>
        internal static string AnalyzerO8Title {
            get {
                return ResourceManager.GetString("AnalyzerO8Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method must returns a collection.
        /// </summary>
        internal static string AnalyzerO8MessageFormat {
            get {
                return ResourceManager.GetString("AnalyzerO8MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method must returns a collection.
        /// </summary>
        internal static string AnalyzerO8Description {
            get {
                return ResourceManager.GetString("AnalyzerO8Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method must returns a collection.
        /// </summary>
        internal static string AnalyzerI7YieldTitle {
            get {
                return ResourceManager.GetString("AnalyzerI7YieldTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method must returns a collection.
        /// </summary>
        internal static string AnalyzerI7YieldMessageFormat {
            get {
                return ResourceManager.GetString("AnalyzerI7YieldMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method must returns a collection.
        /// </summary>
        internal static string AnalyzerI7YieldDescription {
            get {
                return ResourceManager.GetString("AnalyzerI7YieldDescription", resourceCulture);
            }
        }
    }
}
