/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_eeee_Main */

#ifndef _Included_com_eeee_Main
#define _Included_com_eeee_Main
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_eeee_Main
 * Method:    sayHello
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_eeee_Main_sayHello
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
